# models/silver/schema.yml
version: 2

models:
  - name: fct_customers
    description: "Fact table for customers with incremental loading"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: is_vip
        tests:
          - vip_flag

  - name: fct_products
    description: "Fact table for products with incremental loading"
    columns:
      - name: product_id
        description: "Unique ID for each product"
        tests:
          - not_null
          - unique
      - name: sku
        description: "Stock keeping unit"
        tests:
          - not_null
      - name: name
        description: "Product name"
        tests:
          - not_null
      - name: category
        description: "Product category"
      - name: subcategory
        description: "Product subcategory"
      - name: current_price
        description: "Current price of the product"
      - name: currency
        description: "Currency of the price"
      - name: is_discontinued
        description: "Flag if product is discontinued"
      - name: introduced_dt
        description: "Date when the product was introduced"
      - name: discontinued_dt
        description: "Date when the product was discontinued"
