version: 2

models:
  - name: dim_customers
    description: "Dimension for GDPR-safe customer data"
  - name: dim_products
    description: "SCD2 product dimension from snapshot"
  - name: dim_date
    description: "Calendar dimension with derived fields"
  - name: fct_sales
    description: "Fact table joining all dimensions with KPIs"
